# Generated by Django 2.0 on 2017-12-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredienteCorte',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'INGREDIENTE_CORTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
                ('tnombre', models.CharField(db_column='tNombre', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'INGREDIENTES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecetaIngredientecorte',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'RECETA_INGREDIENTECORTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
                ('tnombre', models.CharField(db_column='tNombre', max_length=100)),
                ('norden', models.IntegerField(blank=True, db_column='nOrden', null=True)),
                ('tdetalle', models.TextField(blank=True, db_column='tDetalle', null=True)),
            ],
            options={
                'db_table': 'RECETAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sabores',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
                ('tnombre', models.CharField(db_column='tNombre', max_length=45)),
            ],
            options={
                'db_table': 'SABORES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnicas',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
                ('tnombre', models.CharField(db_column='tNombre', max_length=100)),
            ],
            options={
                'db_table': 'TECNICAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Texturas',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
                ('tnombre', models.CharField(db_column='tNombre', max_length=45)),
            ],
            options={
                'db_table': 'TEXTURAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposdeacompanamiento',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
                ('tnombre', models.CharField(db_column='tNombre', max_length=45)),
            ],
            options={
                'db_table': 'TIPOSDEACOMPANAMIENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposdecorte',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
                ('tnombre', models.CharField(db_column='tNombre', max_length=75, unique=True)),
            ],
            options={
                'db_table': 'TIPOSDECORTE',
                'managed': False,
            },
        ),
    ]
