# Generated by Django 2.0 on 2017-12-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
                ('tnombre', models.CharField(db_column='tNombre', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'INGREDIENTES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
                ('tnombre', models.CharField(db_column='tNombre', max_length=100)),
                ('norden', models.IntegerField(blank=True, db_column='nOrden', null=True)),
                ('tdetalle', models.TextField(blank=True, db_column='tDetalle', null=True)),
            ],
            options={
                'db_table': 'RECETAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
                ('tnombre', models.CharField(db_column='tNombre', max_length=45)),
            ],
            options={
                'db_table': 'SABORES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
                ('tnombre', models.CharField(db_column='tNombre', max_length=100)),
            ],
            options={
                'db_table': 'TECNICAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Textura',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
                ('tnombre', models.CharField(db_column='tNombre', max_length=45)),
            ],
            options={
                'db_table': 'TEXTURAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodeacompanamiento',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
                ('tnombre', models.CharField(db_column='tNombre', max_length=45)),
            ],
            options={
                'db_table': 'TIPOSDEACOMPANAMIENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodecorte',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
                ('tnombre', models.CharField(db_column='tNombre', max_length=75, unique=True)),
            ],
            options={
                'db_table': 'TIPOSDECORTE',
                'managed': False,
            },
        ),
    ]
