# Generated by Django 2.0 on 2017-12-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_ingrediente_receta_sabor_tecnica_textura_tipodeacompanamiento_tipodecorte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metareceta',
            fields=[
                ('cid', models.AutoField(db_column='cId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'METARECETAS',
                'managed': False,
            },
        ),
    ]
